// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: DemoTest

#ifndef _DEMOTEST_UI_H
#define _DEMOTEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_UnitTitle;
extern lv_obj_t * ui_HP;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_mk_png);    // assets\mk.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
